// Carga la configuración de la API desde el archivo config.js
let apiKey = '';
let modelId = '';
$.getScript('config.js', function() {
	apiKey = config.apiKey;
    	modelId = config.modelId;
        });

        // Función para detectar el idioma del archivo PDF
        async function detectarIdioma(data) {
        	// Carga la biblioteca pdf.js para leer el archivo PDF
            	const pdfjsLib = await pdfjsLibLoader();
                	// Lee el archivo PDF
                    	const loadingTask = pdfjsLib.getDocument(data);
                        	const pdf = await loadingTask.promise;
                            	const totalPaginas = pdf.numPages;
                                	// Carga la biblioteca nlp.js para detectar el idioma de cada página del PDF
                                    	const nlp = await NlpJsLoader();
                                        	const idiomas = {};
                                            	for (let i = 1; i <= totalPaginas; i++) {
                                                		const pagina = await pdf.getPage(i);
                                                        		const texto = await pagina.getTextContent();
                                                                		const resultado = await nlp.langid(texto.items.map(item => item.str).join('\n'));
                                                                        		const idioma = resultado[0].lang;
                                                                                		if (idiomas[idioma]) {
                                                                                        			idiomas[idioma]++;
                                                                                                    		} else {
                                                                                                            			idiomas[idioma] = 1;
                                                                                                                        		}
                                                                                                                                	}
                                                                                                                                    	// Devuelve el idioma más común
                                                                                                                                        	const idioma = Object.keys(idiomas).reduce((a, b) => idiomas[a] > idiomas[b] ? a : b);
                                                                                                                                            	return idioma;
                                                                                                                                                }

                                                                                                                                                // Función para traducir el archivo PDF
                                                                                                                                                async function traducirArchivo(data, idiomaDestino) {
                                                                                                                                                	try {
                                                                                                                                                    		// Carga la biblioteca pdf.js para leer el archivo PDF
                                                                                                                                                            		const pdfjsLib = await pdfjsLibLoader();
                                                                                                                                                                    		// Lee el archivo PDF
                                                                                                                                                                            		const loadingTask = pdfjsLib.getDocument(data);
                                                                                                                                                                                    		const pdf = await loadingTask.promise;
                                                                                                                                                                                            		const totalPaginas = pdf.numPages;
                                                                                                                                                                                                    		// Carga la biblioteca nlp.js para traducir el texto de cada página del PDF
                                                                                                                                                                                                            		const nlp = await NlpJsLoader();
                                                                                                                                                                                                                    		const traducciones = [];
                                                                                                                                                                                                                            		for (let i = 1; i <= totalPaginas; i++) {
                                                                                                                                                                                                                                    			const pagina = await pdf.getPage(i);
                                                                                                                                                                                                                                                			const texto = await pagina.getTextContent();
                                                                                                                                                                                                                                                            			const resultado = await nlp.translate(texto.items.map(item => item.str).join('\n'), 'es', idiomaDestino);
                                                                                                                                                                                                                                                                        			traducciones.push(resultado);
                                                                                                                                                                                                                                                                                    		}
                                                                                                                                                                                                                                                                                            		// Crea un archivo PDF con el texto traducido
                                                                                                                                                                                                                                                                                                    		const doc = new jsPDF();
                                                                                                                                                                                                                                                                                                            		traducciones.forEach((texto, index) => {
                                                                                                                                                                                                                                                                                                                    			doc.addPage();
                                                                                                                                                                                                                                                                                                                                			doc.setFontSize(12);
                                                                                                                                                                                                                                                                                                                                            			doc.text(texto, 10, 10);
                                                                                                                                                                                                                                                                                                                                                        		});
                                                                                                                                                                                                                                                                                                                                                                		return doc;
                                                                                                                                                                                                                                                                                                                                                                        	} catch (error) {
                                                                                                                                                                                                                                                                                                                                                                            		// Muestra una alerta si hay un error al traducir el archivo
                                                                                                                                                                                                                                                                                                                                                                                    		alert('Error al traducir el archivo.');
                                                                                                                                                                                                                                                                                                                                                                                            		console.error(error);
                                                                                                                                                                                                                                                                                                                                                                                                    	}
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                        // Función para mostrar la barra de progreso y actualizar su valor
                                                                                                                                                                                                                                                                                                                                                                                                        function mostrarProgreso(valor) {
                                                                                                                                                                                                                                                                                                                                                                                                        	const barraProgreso = $('.progress-bar');
                                                                                                                                                                                                                                                                                                                                                                                                            	barraProgreso.css('width', valor + '%');
                                                                                                                                                                                                                                                                                                                                                                                                                	barraProgreso.attr('aria-valuenow', valor);
                                                                                                                                                                                                                                                                                                                                                                                                                    	barraProgreso.text(valor + '%');
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                        // Función para ocultar la barra de progreso y restablecer su valor
                                                                                                                                                                                                                                                                                                                                                                                                                        function ocultarProgreso() {
                                                                                                                                                                                                                                                                                                                                                                                                                        	const barraProgreso = $('.progress-bar');
                                                                                                                                                                                                                                                                                                                                                                                                                            	barraProgreso.css('width', '0%');
                                                                                                                                                                                                                                                                                                                                                                                                                                	barraProgreso.attr('aria-valuenow', '0');
                                                                                                                                                                                                                                                                                                                                                                                                                                    	barraProgreso.text('');
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                        // Función principal que se ejecuta al cargar el archivo
                                                                                                                                                                                                                                                                                                                                                                                                                                        async function procesarArchivo() {
                                                                                                                                                                                                                                                                                                                                                                                                                                        	// Obtiene el archivo subido por el usuario
                                                                                                                                                                                                                                                                                                                                                                                                                                            	const archivo = $('#archivo')[0].files[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                	if (!archivo) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    		// Muestra una alerta si no se ha seleccionado un archivo
                                                                                                                                                                                                                                                                                                                                                                                                                                                            		alert('Seleccione un archivo PDF para traducir.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	// Obtiene el idioma de origen del archivo PDF
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	const idiomaOrigen = await detectarIdioma(archivo);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	// Obtiene el idioma de destino seleccionado por el usuario
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	const idiomaDestino = $('#idioma-destino').val();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	if (idiomaOrigen === idiomaDestino) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		// Muestra una alerta si el idioma de origen y destino son iguales
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		alert('El idioma de origen y destino son iguales.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	// Traduce el archivo PDF
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	const documentoTraducido = await traducirArchivo(archivo, idiomaDestino);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	if (documentoTraducido) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            		// Descarga el archivo traducido
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    		documentoTraducido.save('traduccion.pdf');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	// Oculta la barra de progreso
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	ocultarProgreso();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Configura el botón de procesar archivo para que inicie la traducción
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $('#procesar-archivo').click(async function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	// Muestra la barra de progreso
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	mostrarProgreso(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	// Procesa el archivo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	await procesarArchivo();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Configura el botón de cancelar para que cancele la traducción y oculte la barra de progreso
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $('#cancelar').click(function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	// Cancela la traducción
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	jsPDF.API.cancel();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	// Oculta la barra de progreso
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	ocultarProgreso();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Función para mostrar una alerta de éxito
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function mostrarAlertaExito(mensaje) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	$('.alert-success').html(mensaje).fadeIn().delay(2000).fadeOut();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Función para mostrar una alerta de error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function mostrarAlertaError(mensaje) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	$('.alert-danger').html(mensaje).fadeIn().delay(2000).fadeOut();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                